package com.johnreg.to_doapp.ui.adapters

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.content.ContextCompat.getColor
import androidx.navigation.findNavController
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.RecyclerView
import com.johnreg.to_doapp.R
import com.johnreg.to_doapp.data.models.Priority
import com.johnreg.to_doapp.data.models.ToDoData
import com.johnreg.to_doapp.databinding.RowLayoutBinding
import com.johnreg.to_doapp.ui.fragments.ListFragmentDirections

class ListAdapter : RecyclerView.Adapter<ListAdapter.ListViewHolder>() {

    private var dataList: List<ToDoData> = emptyList()

    override fun getItemCount(): Int = dataList.size

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ListViewHolder {
        // Inflate the layout for this adapter
        val inflater = LayoutInflater.from(parent.context)
        val binding = RowLayoutBinding.inflate(inflater, parent, false)
        return ListViewHolder(binding)
    }

    override fun onBindViewHolder(holder: ListViewHolder, position: Int) {
        val currentItem = dataList[position]
        holder.bind(currentItem)
    }

    fun setDataList(newDataList: List<ToDoData>) {
        val toDoDiffUtil = ToDoDiffUtil(dataList, newDataList)
        val toDoDiffResult = DiffUtil.calculateDiff(toDoDiffUtil)

        dataList = newDataList
        toDoDiffResult.dispatchUpdatesTo(this)
    }

    fun getItemAt(position: Int): ToDoData = dataList[position]

    inner class ListViewHolder(
        private val binding: RowLayoutBinding
    ) : RecyclerView.ViewHolder(binding.root) {
        fun bind(currentItem: ToDoData) {
            itemView.setOnClickListener {
                // This class is automatically generated by the Safe Args plugin
                // Args suffix - receive the argument | Directions suffix - pass the argument
                val action = ListFragmentDirections.actionListFragmentToUpdateFragment(currentItem)
                itemView.findNavController().navigate(action)
            }

            val color = when (currentItem.priority) {
                Priority.HIGH -> getColor(itemView.context, R.color.red)
                Priority.MEDIUM -> getColor(itemView.context, R.color.yellow)
                Priority.LOW -> getColor(itemView.context, R.color.green)
            }

            binding.priorityIndicator.setCardBackgroundColor(color)
            binding.tvTitle.text = currentItem.title

            if (currentItem.description.isEmpty()) {
                binding.tvDescription.visibility = View.GONE
            } else {
                binding.tvDescription.visibility = View.VISIBLE
                binding.tvDescription.text = currentItem.description
            }
        }
    }

}